version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk1
    ports:
      - "2181:2181"
  kafka1:
    image: kafkaserver
    container_name: ks1
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOSTIP
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_BROKER_ID: 1      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: kafkaserver
    container_name: ks2
    ports:
      - "9092"
    depends_on:
      - zookeeper
      - kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOSTIP
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_BROKER_ID: 2     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: kafkaserver
    container_name: ks3
    ports:
      - "9092"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $HOSTIP
      KAFKA_CREATE_TOPICS: "sampletopic:16:3"
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_BROKER_ID: 3      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  pyclient:
    build: ./pyclient
    container_name: client1
    environment:
      KAFKA_ADVERTISED_SERVERS: "ks1:9092,ks2:9092,ks3:9092"
  cassandra1:
    image: cassandra:3.7
    container_name: cassandra1
    restart: on-failure:10
    environment:
      MAX_HEAP_SIZE: "2G"
      HEAP_NEWSIZE: "256M"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra1"
  cassandra2:
    image: cassandra:3.7
    container_name: cassandra2
    restart: on-failure:10
    depends_on:
      - cassandra1
    environment:
      MAX_HEAP_SIZE: "2G"
      HEAP_NEWSIZE: "256M"
      CASSANDRA_BROADCAST_ADDRESS: "cassandra2"
      CASSANDRA_SEEDS: "cassandra1"
  cassandra3:
    image: cassandra:3.7
    container_name: cassandra3
    restart: on-failure:10
    depends_on:
      - cassandra1
      - cassandra2
    environment:
      MAX_HEAP_SIZE: "2G"
      HEAP_NEWSIZE: "256M"
      CASSANDRA_SEEDS: "cassandra1,cassandra2"
  cassandrainit:
    build: ./cassandrainit
    container_name: cinit
    restart: on-failure:5
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
  spark1:
    build: ./spark
    container_name: spark1
    environment:
      KAFKA_ADVERTISED_SERVERS: "ks1:9092,ks2:9092,ks3:9092"
  flink-master:
    build: 
      context: ./flink
      dockerfile: Dockerfile_flink_master
    ports:
      - "6123"
      - "8081"
    container_name: flink-master
  flink-worker1:
    build:
      context: ./flink
      dockerfile: Dockerfile_flink_worker
    ports:
      - "6121"
      - "6122"
    container_name: flink-worker1
  flink-worker2:
    build:
      context: ./flink
      dockerfile: Dockerfile_flink_worker
    ports:
      - "6121"
      - "6122"
    container_name: flink-worker2

